const CARDS = Object.freeze([
  Object.freeze({
    id: 'recruta_arcano',
    name: 'Recruta Arcano',
    role: 'dano',
    rarity: 'comum',
    damageBase: 12,
    hpBase: 90,
    damage: 12,
    hp: 90,
    description: 'Dano direto e equilibrado.',
  }),
  Object.freeze({
    id: 'curandeira_jade',
    name: 'Curandeira de Jade',
    role: 'suporte',
    rarity: 'comum',
    damageBase: 7,
    hpBase: 115,
    damage: 7,
    hp: 115,
    description: 'Recupera a carta aliada mais ferida.',
  }),
  Object.freeze({
    id: 'falcao_veloz',
    name: 'Falcão Veloz',
    role: 'dps',
    rarity: 'comum',
    damageBase: 15,
    hpBase: 75,
    damage: 15,
    hp: 75,
    description: 'Ataca com velocidade e força.',
  }),
  Object.freeze({
    id: 'aranha_nevoa',
    name: 'Aranha da Névoa',
    role: 'veneno',
    rarity: 'comum',
    damageBase: 10,
    hpBase: 100,
    damage: 10,
    hp: 100,
    description: 'Envenena o alvo por vários turnos.',
  }),
  Object.freeze({
    id: 'cavaleiro_rubro',
    name: 'Cavaleiro Rubro',
    role: 'dano',
    rarity: 'rara',
    damageBase: 24,
    hpBase: 130,
    damage: 24,
    hp: 130,
    description: 'Golpes fortes com boa resistência.',
  }),
  Object.freeze({
    id: 'oraculo_azul',
    name: 'Oráculo Azul',
    role: 'suporte',
    rarity: 'rara',
    damageBase: 15,
    hpBase: 175,
    damage: 15,
    hp: 175,
    description: 'Sustenta a equipe com cura.',
  }),
  Object.freeze({
    id: 'atiradora_cometa',
    name: 'Atiradora Cometa',
    role: 'dps',
    rarity: 'rara',
    damageBase: 29,
    hpBase: 105,
    damage: 29,
    hp: 105,
    description: 'Dano contínuo de alta velocidade.',
  }),
  Object.freeze({
    id: 'serpente_umbra',
    name: 'Serpente Umbra',
    role: 'veneno',
    rarity: 'rara',
    damageBase: 21,
    hpBase: 145,
    damage: 21,
    hp: 145,
    description: 'Aplica veneno e desgasta o inimigo.',
  }),
  Object.freeze({
    id: 'dragao_celeste',
    name: 'Dragão Celeste',
    role: 'dano',
    rarity: 'ultra',
    damageBase: 43,
    hpBase: 220,
    damage: 43,
    hp: 220,
    description: 'Ataques poderosos e muita vida.',
  }),
  Object.freeze({
    id: 'sacerdotisa_estelar',
    name: 'Sacerdotisa Estelar',
    role: 'suporte',
    rarity: 'ultra',
    damageBase: 27,
    hpBase: 275,
    damage: 27,
    hp: 275,
    description: 'Grande suporte para toda a equipe.',
  }),
  Object.freeze({
    id: 'fenda_rasante',
    name: 'Fenda Rasante',
    role: 'dps',
    rarity: 'ultra',
    damageBase: 52,
    hpBase: 180,
    damage: 52,
    hp: 180,
    description: 'Dano explosivo em sequência.',
  }),
  Object.freeze({
    id: 'hidra_corrosiva',
    name: 'Hidra Corrosiva',
    role: 'veneno',
    rarity: 'ultra',
    damageBase: 38,
    hpBase: 245,
    damage: 38,
    hp: 245,
    description: 'Veneno intenso que continua causando dano.',
  }),
]);

const CARDS_BY_ID = new Map(CARDS.map((card) => [card.id, card]));

function findCard(cardId) {
  return CARDS_BY_ID.get(cardId);
}

module.exports = { CARDS, CARDS_BY_ID, findCard };
